### ISSUE TITLE
update plugin for QGIS 2.0 API

### ISSUE THREAD

**Issue by gubuntu** [springmeyer/quantumnik#6]
An error has occured while executing Python code:

Traceback (most recent call last):
  File "/home/gavin/.qgis2/python/plugins/quantumnik/quantumnik.py", line 345, in load_xml
    self.set_canvas_from_mapnik()
  File "/home/gavin/.qgis2/python/plugins/quantumnik/quantumnik.py", line 261, in set_canvas_from_mapnik
    crs.createFromEpsg(int(epsg))
AttributeError: 'QgsCoordinateReferenceSystem' object has no attribute 'createFromEpsg'

Python version:
2.7.3 (default, Sep 26 2012, 21:53:55) 
[GCC 4.7.2]

QGIS version:
1.9.0-Master Master, exported

**Comment by springmeyer** [comment]
thanks for the report.

**Comment by springmeyer** [comment]
looks pretty involved: http://hub.qgis.org/wiki/quantum-gis/Python_plugin_API_changes_from_18_to_20

**Comment by springmeyer** [comment]
http://nathanw.net/2013/09/22/broken-qgis-plugins/
